### ISSUE TITLE
Failed to get address info of cibersortx.stanford.edu: Resource temporarily unavailable 

### ISSUE THREAD

**Issue by martion12** [digitalcytometry/ecotyper#10]
Hello, Thank you for sharing such a great job. This is very helpful to my research.
But I have a problem in the process of using EcoTyper Tutorial 4  step1 Cell type fraction estimation. The error is “Failed to get address info of cibersortx.stanford.edu: Resource temporarily unavailable “, I want to know that how this error is caused ? and how can I solve this error
I hope to get your reply. Thank you again for your work

**Comment by BALuca** [comment]
Hey, thank you for your interest in EcoTyper. We haven't encountered this issue before, but my guess is that it is an issue with the internet connection or DNS lookup on your server, encountered when trying to authenticate the CIBERSORTx token. If your internet connection seems fine, please try the following command: docker run cibersortx/fractions. It should produce the output bellow. If it doesn't produce that output, then it is likely a DNS/ internet connection issue. You can try to address it by following these steps: https://robinwinslow.uk/fix-docker-networking-dns (do it at your own risk!). If it does show the output below but EcoTyper still won't run, please reach us on ecotyper.stanford@gmail.com.

![image](https://user-images.githubusercontent.com/36973687/150619825-b681c25c-3032-45b2-89a4-b13e03229cbc.png)
