### ISSUE TITLE
recovery our custom discovery have a problem

### ISSUE THREAD

**Issue by Eve12126** [digitalcytometry/ecotyper#20]
Hi,

When  using bulk data to run "recovery",  we select "Carcinoma", no error will be reported. But when we use the same bulk data to run "recovery" our custom discovery, there is such an error: "Error in `[<-.data.frame`(`*tmp*`, , col, value = 1L) : replacement has 1 row, data has 0 Calls: "

Best.

**Comment by BALuca** [comment]
Hi,

Would it be possible to send the data you tried, the command line and the R version you used to ecotyper.stanford@gmail.com, so that we can investigate the issue?

Best,
The EcoTyper team

**Comment by Eve12126** [comment]
Thank you, we have solved the above problem. But we now have a new problem.When I reached the second step-’Step 2 (cell state discovery on correrlation matrices): Aggregating NMF results...‘, it reported the following error-’Error in consensus + nrun(x) * consensus(x) : non-conformable arrays
Execution halted‘, Can you help me answer what is causing this?Thank you for answering！

**Comment by BALuca** [comment]
Hi,
I suspect that it is a formatting issue with the input data or an issue in the configuration files. Would it be possible to send us the config file and the top 10 rows of your input file at ecotyper.stanford@gmail.com?
Best,
The EcoTyper team
