### ISSUE TITLE
issue with EcoTyper_discovery_scRNA.R "Error in fastCor(scaled_data) : invalid nSplit: 0“

### ISSUE THREAD

**Issue by QianhuiXu** [digitalcytometry/ecotyper#21]
Hello,

ecotyper is a wonderful tool！

I got an issue when running EcoTyper_discovery_scRNA.R with our scRNA data.

My command :  Rscript EcoTyper_discovery_scRNA.R -c config_discovery_scRNA.yml

output: Step 1 (extract cell type specific genes)...
[1] "Epithelial.cells"
Warning message:
row_wilcoxon_twosample: 21736 of the rows had less than 1 remaining finite "y" observation.
First occurrence at row 1 
Step 1 (extract cell type specific genes) finished successfully!

Step 2 (cell state discovery on correrlation matrices): Calculating correlation matrices...
Warning message:
There are more than 2500 single cells available for cell type 'Epithelial.cells'. Subsampling to 2500 cells.
 
Filtering 'Epithelial.cells' profiles for cell type specific genes...
---> Checking zero-variance data...
--->  Total number of variables:  2500
--->  WARNING: 2500 variables found with zero variance
---> Maximum number of splits: floor(n/2) = 0
---> WARNING: number of splits nSplit > 0
---> WARNING: using maximum number of splits: nSplit = 0
Error in fastCor(scaled_data) : invalid nSplit: 0
Execution halted
Error in RunJobQueue() : 
  EcoTyper failed. Please check the error message above!
Execution halted
![a5a33256794df3440d6902c854cc313](https://user-images.githubusercontent.com/69391572/163715072-fd8a7ed9-34b7-4d2d-8d10-119cf5cb00ed.png)

I'm really at a loss as to how to proceed, and any guidance would be much appreciated!

Thank you for your kind help!

**Comment by BALuca** [comment]
Hi,

Thank you for your interest in EcoTyper! My sense is that there is an issue with the format of the input data or the configuration file. Would you be able to send us the following data at ecotyper.stanford@gmail.com:
* The configuration file (config_discovery_scRNA.yml) you used.
* The annotation file, e.g. "example_data/scRNA_CRC_annotation.txt".
* The top 5-10 rows of the expression matrix you tried.
* R version (or sessionInfo()).

Best,
The EcoTyper team

**Comment by QianhuiXu** [comment]
Thank you for your attention and kind help!
I have solved this issue by using scRNA data with several celltypes. And I think this issue may be caused by scRNA data with only one celltype.

**Comment by QianhuiXu** [comment]
Dear EcoTyper team,

 

We want to use ecotyper in our scRNA-Seq dataset. But I was confused with the differences of Tutorial 2 with Tutorial 5. Which analysis pipeline should I follow to analyze cell type-specific transcriptional states and their co-association patterns in our scRNA-Seq dataset?

I'm really at a loss as to how to proceed, and any guidance would be much appreciated!

 

Sincerely,

Qianhui Xu
