### ISSUE TITLE
The differences of Tutorial 2 with Tutorial 5

### ISSUE THREAD

**Issue by QianhuiXu** [digitalcytometry/ecotyper#23]
Dear EcoTyper team,

We want to use ecotyper in our scRNA-Seq dataset. But I was confused with the differences of Tutorial 2 with Tutorial 5. Which analysis pipeline should I follow to analyze cell type-specific transcriptional states and co-association patterns in our scRNA-Seq dataset?
I'm really at a loss as to how to proceed, and any guidance would be much appreciated!

Sincerely,
Qianhui Xu

**Comment by BALuca** [comment]
Hi,

Tutorial 2 allows you to label your single cells to the cell states that we already defined in [carcinoma](https://www.cell.com/cell/fulltext/S0092-8674(21)01061-8) or [lymphoma](https://linkinghub.elsevier.com/retrieve/pii/S1535-6108(21)00451-7). Tutorial 5 allows you to discover **de-novo** cell states and ecotypes from your scRNA-seq data. So, my sense is that you want to try Tutorial 5.

Bogdan
