### ISSUE TITLE
Ecotyper crashes in R 4.2 stable

### ISSUE THREAD

**Issue by semenko** [digitalcytometry/ecotyper#24]
Setting `digits=0` in `format()` is no longer supported, resulting in Ecotyper crashes:

```
Error in prettyNum(.Internal(format(x, trim, digits, nsmall, width, 3L,  : 
  invalid value 0 for 'digits' argument
```

https://cran.r-project.org/doc/manuals/r-devel/NEWS.html#:~:text=BUG%20FIXES-,Setting%20digits%20%3D%200,-in%20format()

https://bugs.r-project.org/show_bug.cgi?id=18098

**Comment by BALuca** [comment]
Hi,

Thanks for reporting this issue. We have been able to isolate and fix it.

Best,
The EcoTyper team
