### ISSUE TITLE
error in 'Tutorial 1'

### ISSUE THREAD

**Issue by zhangch365** [digitalcytometry/ecotyper#25]
dear Ecotyper team，
     We've got our own sc-ecotyper, but when we used the bulk data to recovery it, it reported the following error, 
'Error in (function (classes, fdef, mtable)  : 
  unable to find an inherited method for function ‘draw’ for signature ‘"NULL"’
Calls: draw ->  ' Anonymous'
Execution halted
Error in RunJobQueue() : 
  EcoTyper failed. Please check the error message above!
Execution halted'.
     we've got a few sc-ecotypers,the same bulk data succeeded in several others, but in this one kept reporting errors.
     I would appreciate it if you could provide some advice，thank you very much！

**Comment by BALuca** [comment]
Hi,

I suspect that none of the bulk samples are assigned to ecotypes or cell states for a given cell types for this version of sc-ecotyper. Therefore, EcoTyper was crashing when trying to plot a NULL matrix. I updated the code to throw a more informative error message when this happens. Please let us know if you still get this error after trying the latest version of the code from github.

Best,
The EcoTyper team
