### ISSUE TITLE
bulk recovery questions

### ISSUE THREAD

**Issue by zhangch365** [digitalcytometry/ecotyper#27]
dear EcoTyper team，
    When we run the bulk data with our own single-cell ‘discovery’ data, there are a total of five hundred samples, and finally only a few cases are assigned to our own defined ecotype, can we adjust some parameters so that more samples can be distributed to the ecotype?
thanks a lot！

**Comment by BALuca** [comment]
Hi,

We noticed this behavior when the ecotypes discovered from single-cells are not robust enough. This can happen when the number of scRNA-seq samples used for discovery is small. Two parameters from the configuration file that can be tweaked to try to improve the results are: "Cophenetic coefficient cutoff" which allows you to modulate the granularity of cell states, in case the default value under/over-estimates the number of states; and "Jaccard matrix p-value cutoff", which could increase the stringency of co-associations patterns when discovering ecotypes. In addition to these parameters, once can evaluate the granularity of cell annotations to cell types. Depending on the biological system analyzed, one might want to merge subpopulations of the same larger population, or split too broad cell type definitions into subpopulations.

Best,
The EcoTyper team
