### ISSUE TITLE
could the ecotyper apply to the microarray data directly?

### ISSUE THREAD

**Issue by lzz-123** [digitalcytometry/ecotyper#28]
According to analysis tutorial, EcoTyper takes as input a bulk gene expression table from RNA-seq or microarray data with the following formatting requirements: Data values can be TPM, FPKM, log2(TPM), or log2(FPKM). My question is, can we use microarray data as input without transforming it into FPKM/TPM format? I have no idea how to transform the microarray data into FPKM/TPM format.

**Comment by BALuca** [comment]
Hi,

Apologize for the confusion, there is no requirement to transform microarray data to FPKM/TPM. EcoTyper should work on microarray data as it is.

Bogdan
