### ISSUE TITLE
problems in tutorial 1

### ISSUE THREAD

**Issue by lzz-123** [digitalcytometry/ecotyper#30]
Hi,

When using the "bulk_lung_data. txt" to run "recovery", we select "Carcinoma", there is an error: "Error in read.table(file = file, header = header, sep = sep, quote = quote,  : 
  no lines available in input "
No error occurred when we run "recovery" using "bulk_lymphoma_data. txt"

Best.

**Comment by BALuca** [comment]
Hi,

We have not been able to reproduce the behavior. Can you please indicate the command line used?

Best,
The EcoTyper team
