### ISSUE TITLE
EcoTyper State Recovery ScRNAseq Error  

### ISSUE THREAD

**Issue by dkwon6** [digitalcytometry/ecotyper#31]
Hello, 

I've been trying to look at scRNAseq data of carcinomas previously published in Lucas et al. Cell 2021. I've had some trouble with putting through the scRNAseq data of Puram et al. 2017 (GSE103322), which was used in the aforementioned publication. After downloading and importing the gene count matrix into R, I separate the metadata (first 5 rows) and transpose it to create the annotation file with the appropriate ID and CellType column. Next, I convert all columns, save the gene IDs, to numeric as the authors report their counts in log2(TPM/10 +1) and I wish to convert back to TPM. I checked the gene matrix for NaNs, INFs, NAs and characters, which all checked out. I put the gene matrix and annotation file through EcoTyper and encounter the following error: 

Error in NMF:::std.divergence.update.h(v, w, h, nbterms = nb, ncterms = nc,  :
  REAL() can only be applied to a 'numeric', not a 'logical'
Calls: NMFpredict ... .local -> run -> run -> .local -> updateFun -> <Anonymous>
In addition: Warning messages:
1: In max(target, na.rm = TRUE) :
  no non-missing arguments to max; returning -Inf
2: In min(x, na.rm = TRUE) :
  no non-missing arguments to min; returning Inf
3: In min(rowSums(x, na.rm = TRUE), na.rm = TRUE) :
  no non-missing arguments to min; returning Inf
Timing stopped at: 0.031 0 0.04
Execution halted
Error in RunJobQueue() :
  EcoTyper failed. Please check the error message above!
Execution halted

I've tried putting through the gene matrix without conversion to TPM and received the same error. I've put through some of the other scRNAseq data through EcoTyper and haven't seen this error ever. I am hoping to get some support regarding this issue as it is not documented in the readme file and searching on Biostars, Google and StackOverflow didn't yield anything useful. Thank you!

**Comment by BALuca** [comment]
Hi,

Apologize for the delay in responding to this. I suspect this error has to do with a formatting issue of the input data. Would you be able to send us the top 10 rows of the input expression matrix and the annotation file at ecotyper.stanford@gmail.com, to debug the problem?

Best,
The EcoTyper team
