### ISSUE TITLE
Tutorial 6 error with CODEFACS results

### ISSUE THREAD

**Issue by biobug16** [digitalcytometry/ecotyper#32]
Hi Team,
I used CODEFACS for deconvolution and trying to use its output as an input for Ecotyper using tutorial_6. As recommended I used all the genes and their deconvolved gene expression values as per the tutorial but getting following error at the "Step 2 (cell state discovery): Preparing the NMF input..." for most of my cell types:

Not filtering 'Myeloid_2' profiles for cell type specific genes...
Error in cut.default(mean, breaks = c(-Inf, unique(quantile(mean, seq(0.1,  : 
  'breaks' are not unique
Calls: get_variable_genes ... with -> with.default -> eval -> eval -> cut -> cut.default
Execution halted
Not filtering 'T.cell.Group4' profiles for cell type specific genes...
Error in cut.default(mean, breaks = c(-Inf, unique(quantile(mean, seq(0.1,  : 
  'breaks' are not unique
Calls: get_variable_genes ... with -> with.default -> eval -> eval -> cut -> cut.default
Execution halted
Error in RunJobQueue() : 
  EcoTyper failed. Please check the error message above!
Execution halted

**PS: I also tried to used 500 most variable genes from every cell type in that case I am getting a different error:**
Step 2 (cell state discovery): Running NMF (Warning: This step might take a long time!)...
Error in if (m < 0) { : missing value where TRUE/FALSE needed
Calls: posneg -> nneg -> nneg -> .local
Execution halted
Error in if (m < 0) { : missing value where TRUE/FALSE needed
Calls: posneg -> nneg -> nneg -> .local
Execution halted
Error in if (m < 0) { : missing value where TRUE/FALSE needed
Calls: posneg -> nneg -> nneg -> .local
Execution halted

I am using following command"
Rscript EcoTyper_discovery_presorted.R -c config_discovery_presorted.yml

Please help and guide me how can I troubleshoot tis issue.
Thank you

**Comment by BALuca** [comment]
Hi,

Apologize for the delay in replying this! There seems to be some issue with the format or value distribution of the input data. I was wondering if it would be possible to share a reproducible example at ecotyper.stanford@gmail.com so that we have a look? Ideally the version with all the genes.

Best,
The EcoTyper team
