### ISSUE TITLE
Failed to connect to cibersortx.stanford.edu:80: Connection timed out

### ISSUE THREAD

**Issue by kaizen89** [digitalcytometry/ecotyper#36]
I have an error that is probably related to proxy settings as the problem disappears when I connect with a private network.
I've already set the proxy settings in Rprofile and in env variables. I tried multiple things with no luck. Any help would be appreciated.
```
Rscript EcoTyper_discovery_bulk.R -c config_discovery_bulk.yml

Step 1 (cell type fraction estimation): Running CIBERSORTxFractions on the discovery dataset...
Running CIBERSORTx fractions with no batch correction, using the 'TR4' signature matrix and 'MyDiscovery' dataset.
Running on docker...
>Running CIBERSORTxFractions...
>[Options] username: abdenour.abbas@curie.fr
>[Options] token: 2d15afd342606b28f5523a2a75836229
>[Options] mixture: /src/data/mixture.txt
>[Options] sigmatrix: /src/data/sigmatrix.txt
>[Options] sourceGEPs: /src/data/sourceGEPs.txt
>[Options] verbose: TRUE
terminate called after throwing an instance of 'std::system_error'
  what():  Failed to connect to cibersortx.stanford.edu:80: Connection timed out
Error: 
Execution halted
Error: 
Execution halted
Error in RunJobQueue() : 
  EcoTyper failed. Please check the error message above!
Execution halted
```

**Comment by BALuca** [comment]
Hi,

EcoTyper uses CIBERSORTx for the first two steps of the workflow, fraction estimation and in silico purification. In order for CIBERSORTx to run, it needs to be able to connect to the website to check the tokens. It seems that due to network configuration issues on your system, it cannot perform this validation. Unfortunately, we cannot help with this. We would suggest to contact your local network administrator. If the settings are correct, and you are still encountering issues, please contact the CIBERSORTx team: https://cibersortx.stanford.edu/contact.php.

Best,
The EcoTyper team

**Comment by Sawakotx** [comment]
Hi~ 
I also try to run tutorial 4 and I met a problem about step 1. I'm not setting 'CIBERSORTx fractions Singularity path' but it didn't run on default Docker, instead it shows that it wants to run on Singularity. It seems to be wrong but I really cannot find the relevant solution. 😭
If you have any clues or suggestions, you are more than welcome, I'm looking forward to them!!! Thanks in advance~
@BALuca @kaizen89 
The details are as below.  


1. There is **pipeline setting**:
![5977a1ac19f8fbbd944b0052b45c66d7](https://github.com/digitalcytometry/ecotyper/assets/82040209/70584910-2336-41be-9dcb-4c304b589f5e)

2. There is **output information**:
`Rscript EcoTyper_discovery_bulk.R -c local_config_discovery_bulk.yml

Step 1 (cell type fraction estimation): Running CIBERSORTxFractions on the discovery dataset...
Running CIBERSORTx fractions with no batch correction, using the 'TR4' signature matrix and 'Test_Discovery' dataset.
Running on singularity...
sh: singularity: command not found
Warning message:
In system(cmd_line) `
