### ISSUE TITLE
Adapt cophenetic coefficient (CC) threshold per cell type

### ISSUE THREAD

**Issue by LeonHafner** [digitalcytometry/ecotyper#37]
Hi there,
after processing my scRNA-Seq dataset with the discovery pipeline I checked the plots, especially the rank plot and the cut off for the CC threshold. After visual inspection it seems reasonable to choose different CC thresholds for some cell types than for others as the graph declines differently for each cell type. Is this possible with EcoTyper or is it only possible to set one global threshold for all cell types?

Thanks!

**Comment by BALuca** [comment]
Hi,

Thanks for your interest in EcoTyper. The current version of EcoTyper only allows to set a global Cophenetic cutoff, shared by all cell types. However, if the automatic selection heuristic is not appropriate for some cell types, one could manually edit file "EcoTyper/<discovery_dataset>/Cell_type_specific_genes/Analysis/rank_selection/rank_data.txt" to adjust the number of states per cell type. Assuming that you are following Tutorial 5, after adjusting the number of cell states, you can restart the EcoTyper pipeline from step 4 onwards. This means that you would need to also edit the configuration file field: "Pipeline steps to skip : [1,2,3]". I hope it helps.

Best,
The EcoTyper team
