### ISSUE TITLE
about Token of CIBERSORTx for docker images

### ISSUE THREAD

**Issue by xflicsu** [digitalcytometry/ecotyper#4]
We try to use ecotyper in our scRNA-Seq datasets with de novo model in ecotyper.
We need the Token of CIBERSORTx for docker images. And we have asked for the Token from the website.
Could you share us that file?

**Comment by BALuca** [comment]
Hi. Can you please send us your email address at: ecotyper.stanford@gmail.com?

**Comment by xflicsu** [comment]
> [ecotyper.stanford@gmail.com](mailto:ecotyper.stanford@gmail.com)?

Thanks for your help

**Comment by QianhuiXu** [comment]
Could you share me the Token of CIBERSORTx? 
My eamil address was qianhuixu@zju.edu.cn
Thank you for your kind help!

**Comment by QianhuiXu** [comment]
@BALuca @xflicsu 
Could you share me the Token of CIBERSORTx? 
My eamil address was qianhuixu@zju.edu.cn
Thank you for your kind help!

**Comment by aiminXie** [comment]
@BALuca 
Hello, could you please share the Token with me as well?
My email address is aiminxie_1993@hrbmu.edu.cn
Thanks!

**Comment by diyang1354** [comment]
@xflicsu @BALuca 
Could you please share the token with me at coeyangdi@pku.edu.cn as well?

**Comment by dufeng311** [comment]
@xflicsu @BALuca 
Could you please share the token with me at d609218518@126.com as well?
Thank you for your kind help!

**Comment by sayhello854123** [comment]
Could you please share the token with me at sayhello854123@gmail.com as well?

**Comment by taohuiying** [comment]
Hi
Could you please share the token with me at thy17852830991@163.com as well?

**Comment by taohuiying** [comment]
@xflicsu @BALuca @aiminXie @diyang1354 @sayhello854123 
Could you please share the token with me at thy17852830991@163.com as well? 
Thank you!
Please please please

**Comment by yueqinhe** [comment]
@xflicsu @BALuca @aiminXie @diyang1354 @sayhello854123
My token already expired last month and when I apply for the new one, there is no response from the team for a long time. Could you please share the token with me at y.he@maastrichtuniveristy.nl? Thank you very much!

**Comment by xiaoxiao-tianjin** [comment]
Could you please share the token with me at yangxx@tmu.edu.cn as well?
Thank you!
Please please please

**Comment by xiaoxiao-tianjin** [comment]
@xflicsu @BALuca @aiminXie @diyang1354 @sayhello854123
Could you please share the token with me at [yangxx@tmu.edu.cn](mailto:yangxx@tmu.edu.cn) as well?
Thank you!
Please please please

**Comment by UnlimitedW** [comment]
@xflicsu @BALuca @aiminXie @diyang1354 @sayhello854123
We have applied for the token for months but still pending approval. There was also no reply to our email message. Could you please share the token and the docker with me at xingyuanwu@hotmail.com? 
Our article received minor revision which really need the result of Ecotype to meet the reviewer's expectation and it is really time sensitive.
Thank you very much!

**Comment by erinlbrown** [comment]
@UnlimitedW could you submit a new request through CSx? I do not see one pending. Also, if you have an academic email address you could use instead it may be helpful.

**Comment by UnlimitedW** [comment]
Thank you very much for the reply and help. I have submitted a request using the account: ***@***.*** for CSx months ago but still pending approval.

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: Erin Brown ***@***.***>
发送时间: Wednesday, November 20, 2024 1:57:52 PM
收件人: digitalcytometry/ecotyper ***@***.***>
抄送: UnlimitedW ***@***.***>; Mention ***@***.***>
主题: Re: [digitalcytometry/ecotyper] about Token of CIBERSORTx for docker images (Issue #4)


@UnlimitedW<https://github.com/UnlimitedW> could you submit a new request through CSx? I do not see one pending. Also, if you have an academic email address you could use instead it may be helpful.

―

**Comment by niejinglan** [comment]
My token has just expired recently and I need to do an analysis with cibersort. Could you please share the token with me at njl0825@126.com? Very appreciate of that!

**Comment by Wang-Fanchen** [comment]
@niejinglan @erinlbrown @BALuca @xflicsu @aiminXie I applied for a token from CSx several months ago, but I haven't received any results yet. Do you have any available tokens that I can use? I would be extremely grateful.

**Comment by niejinglan** [comment]
I'd like to help you but I haven't got any results either. Sorry







| |
njl0825
|
|
***@***.***
|
---- Replied Message ----
| From | ***@***.***> |
| Date | 2/27/2025 22:23 |
| To | ***@***.***> |
| Cc | ***@***.***>,
***@***.***> |
| Subject | Re: [digitalcytometry/ecotyper] about Token of CIBERSORTx for docker images (Issue #4) |

@***@***.***@***@***.***@aiminXie I applied for a token from CSx several months ago, but I haven't received any results yet. Do you have any available tokens that I can use? I would be extremely grateful.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you were mentioned.Message ID: ***@***.***>

Wang-Fanchen left a comment (digitalcytometry/ecotyper#4)

@***@***.***@***@***.***@aiminXie I applied for a token from CSx several months ago, but I haven't received any results yet. Do you have any available tokens that I can use? I would be extremely grateful.

**Comment by erinlbrown** [comment]
@niejinglan, could you kindly confirm the token request has been submitted to CSx with the email you've provided? I do not see one pending. @UnlimitedW, the email address you provided above does not show. If you have not yet received a token, could you confirm the email address? @Wang-Fanchen could you kindly share your email address under which you've requested the token? 

Requests or email address details can also be sent to cibersortx@gmail.com

**Comment by dingzetao** [comment]
@BALuca @xflicsu @diyang1354 @erinlbrown @aiminXie 
I submitted a request for these tokens via the CIBERSORTx website over a month ago, but my application still shows "Token and instruction access pending approval." I have also followed up via email with the CIBERSORTx team but have not received any response.
Could you please share the token with me at dingzetao@sjtu.edu.cn as well?
Thank you very much!

**Comment by mbih0701** [comment]
@xflicsu @BALuca@diyang1354 @erinlbrown @aiminXie
Could you please share the token with me at 3020226046@tju.edu.cn as well?
Thank you for your kind help!

**Comment by TTGACA-dev** [comment]
Hi @erinlbrown, I've submitted a CIBERSORTx token request (from: xuzhy57@mail2.sysu.edu.cn), but it's still "pending approval." I also followed up by email but haven't heard back. Could you please confirm if the request was received? Any help is greatly appreciated!

@xflicsu @BALuca @mbih0701 @dingzetao @Wang-Fanchen @niejinglan Could you please share the token with me at [xuzhy57@mail2.sysu.edu.cn] as well if possible? Thank you for your kind help!
