### ISSUE TITLE
Question about normalized scaled matrix

### ISSUE THREAD

**Issue by seigfried** [digitalcytometry/ecotyper#40]
Hello I am trying out Ecotyper to analyze single cell data and I read that it needs a normalized matrix
I have used Scanpy and the following steps

    sc.pp.normalize_total(adata,target_sum=1e4)
    # sc.pp.log1p(adata)
    # sc.pp.regress_out(adata, ['n_counts', 'percent_mito'])
    # sc.pp.scale(adata, `max_value=10)

Can I just leave it at normalization and not do the rest? Will it affect the analysis if i do not log, regress and scale the data?

Thanks

**Comment by BALuca** [comment]
Hi,

EcoTyper expects normalized, but non-scaled data. If the maximum value in the expression matrix > 50, EcoTyper performs log-normalization and scaling to unit variance. If maximum <= 50, EcoTyper only performs scaling. So, I would comment out the second line in your snippet. If you think that regressing out n_counts and percent_mt is important, you could comment out the third line too. Either of these two outputs could be used as input for EcoTyper.

Best,
The EcoTyper team
