### ISSUE TITLE
scRNA Discovery step 8 state matching of `H` fails

### ISSUE THREAD

**Issue by NoahHenrikKleinschmidt** [digitalcytometry/ecotyper#46]
Hello there (again^^) 

Since it seems my new favorite hobby to open tickets here, I have another issue I am struggling with. This time it is another dataset than the previous one. Steps 1-7 apparently went smoothly without issues (EcoTyper ran o/n without crashing at least, and no `RunJobQueue` was commented out this time). If it helps, the full slurm output (including some logs I manually added here and there) is [available via pastecode.io](https://pastecode.io/s/u7m37pq8).  In summary, step 8 fails to run `ecotypes_assign_samples_scRNA.R` successfully with the error:

```
Error in H[match(mapping$InitialState, rownames(H)), ] : 
  wrong number of dimensions 
Ausführung angehalten
Error in RunJobQueue() : 
  EcoTyper failed. Please check the error message above!
Ausführung angehalten
```
> Again, I paraphrased some of the errors that were originally in German...

I began adding various logs to `ecotypes_assign_samples_scRNA.R`, which I am unsure how to interpret.
If I understand the code correct, the purpose of the lines below is to subset `H` to only rows which match in some Initial state and then reset the names to their final state. 

```
[ line 61 ]
H =H[match(mapping$InitialState, rownames(H)),]
rownames(H) = mapping$State
```

Strangely, the logs reveal that while this process seems to work for some cell types for others (or at least one) it fails although the logs seem to be the same for a cell line that works (Hepatic_stellate_cells) and the one that fails (Hepatoblasts):

```
[ ... ]
INFO [2022-08-08 15:47:36] ----------------------------------------------------------
INFO [2022-08-08 15:47:36] Assembling data from:  Hepatic_stellate_cells
INFO [2022-08-08 15:47:38] mapping was read with shape:  7, 2
INFO [2022-08-08 15:47:38] H was read with shape:  10, 17
INFO [2022-08-08 15:47:38] H has these row.names:  IS01, IS02, IS03, IS04, IS05, IS06, IS07, IS08, IS09, IS10
INFO [2022-08-08 15:47:38] initial states are:  IS03, IS08, IS04, IS09, IS02, IS06, IS07
INFO [2022-08-08 15:47:38] matching states and row.names as:  3, 8, 4, 9, 2, 6, 7    # <- matches are found here
INFO [2022-08-08 15:47:38] this are the InitialState and State within mapping: 
  InitialState State
1         IS03   S01
2         IS08   S02
3         IS04   S03
4         IS09   S04
5         IS02   S05
6         IS06   S06
7         IS07   S07
INFO [2022-08-08 15:47:38] (after matching) H has these row.names:  S01, S02, S03, S04, S05, S06, S07
INFO [2022-08-08 15:47:38] (pre assembly) Assembling all_H, which has shape:  8, 16
INFO [2022-08-08 15:47:38] (after assembly) Assembling all_H, which has shape:  15, 16  and names:  Cholangiocytes_S01, Cholangiocytes_S02, Endothelial_cell_S01, Endothelial_cell_S02, Endothelial_cell_S03, Endothelial_cell_S04, Endothelial_cell_S05, Endothelial_cell_S06, Hepatic_stellate_cells_S01, Hepatic_stellate_cells_S02, Hepatic_stellate_cells_S03, Hepatic_stellate_cells_S04, Hepatic_stellate_cells_S05, Hepatic_stellate_cells_S06, Hepatic_stellate_cells_S07
INFO [2022-08-08 15:47:38] ----------------------------------------------------------
INFO [2022-08-08 15:47:38] Assembling data from:  Hepatoblasts
INFO [2022-08-08 15:47:40] mapping was read with shape:  3, 2
INFO [2022-08-08 15:47:40] H was read with shape:  5, 2
INFO [2022-08-08 15:47:40] H has these row.names:  IS01, IS02, IS03, IS04, IS05
INFO [2022-08-08 15:47:40] initial states are:  IS04, IS01, IS05
INFO [2022-08-08 15:47:40] matching states and row.names as:  NA, NA, NA            # <- no matches are found here
INFO [2022-08-08 15:47:40] this are the InitialState and State within mapping: 
  InitialState State
1         IS04   S01
2         IS01   S02
3         IS05   S03
Fehler in H[match(mapping$InitialState, rownames(H)), ] : 
  falsche Anzahl von Dimensionen
Ausführung angehalten
Fehler in RunJobQueue() : 
  EcoTyper failed. Please check the error message above!
Ausführung angehalten
```

It seems odd that the initial states and row names in both cases visually look okey and also the table of InitialState and State from the mapping does not suggest a reason for this. It could be that there is some kind of whitespace in either the row names or states which prevent matching, but such a bug should have affected all cell types not only one (or some?) of them.  Again, the full output file is [available at pastecode.io](https://pastecode.io/s/3f81gjen) (just a few more entries like the one I pasted up there).

Would you happen to have an idea what is going wrong here? It seems odd that the pipeline seemingly went smoothly through 90% of the process and only at the end starts to fail due to "malformed data files"? 

Thanks again, 
Noah

**Comment by BALuca** [comment]
Hi Noah,

Apologize again for the issues. Judging by the logs, it seems that the H matrix has only 2 columns, meaning that heaptoblasts are coming from two samples only. The low number of samples was causing the crash. I think that the commit that I just pushed should fix the issue. Please let me know if you still encounter problems.

Best,
The EcoTyper team

**Comment by NoahHenrikKleinschmidt** [comment]
Hey there, 

Thanks a lot for the reply, I have pulled the repo again and have submitted the job for-rerunning (has been going on for an hour), I will post an update once it's finished 👍

**Comment by NoahHenrikKleinschmidt** [comment]
Yes, indeed I can confirm that the pipeline finishes now all 8 steps successfully! 🥳
Thank you very much 🌼
