### ISSUE TITLE
Ecotyper crash during Step 2 (cell state discovery) of tutorial 6

### ISSUE THREAD

**Issue by biobug16** [digitalcytometry/ecotyper#47]
Hi @BALuca and Team,
I used CODEFACS for deconvolution and trying to use its output as an input for Ecotyper using tutorial_6. As recommended I used all the genes and their deconvolved gene expression values as per the tutorial but getting following error at the "Step 2 (cell state discovery): Preparing the NMF input..."

Error in RunJobQueue() : 
  EcoTyper failed. Please check the error message above!
Execution halted

Can you please guide what does this mean and how to resolve it?

**Comment by BALuca** [comment]
Hi,

Is this ticket related to [the previous one](https://github.com/digitalcytometry/ecotyper/issues/32)? If not, would it be possible to share a reproducible example at ecotyper.stanford@gmail.com?

Best,
The EcoTyper team
