### ISSUE TITLE
Is the concept of ecotype suitable for chronic diseases?

### ISSUE THREAD

**Issue by PiaoyangGuohai1** [digitalcytometry/ecotyper#48]
Hello, I am very interested in the concept of Ecotyper. Can I apply it to chronic diseases? such as Heart failure. 

If I can try it, what should I pay attention to? 

If can't, what is the reasons? Are there differences in biological background?

Thanks.

**Comment by BALuca** [comment]
Hi,

We have not tested EcoTyper in chronic diseases. However, we are confident that the concept can be extended beyond cancer. I do not anticipate any special requirements when applying EcoTyper to chronic disease. Like for cancer data, one would want to make sure that the results are sound, by validating them in independent data.

Best,
The EcoTyper team
