### ISSUE TITLE
Possible bug report in EcoTyper_discovery_scRNA.R pipeline

### ISSUE THREAD

**Issue by czlcaltech** [digitalcytometry/ecotyper#5]
Hello, thanks for your great tools. I used it to discover ecotype differences between 2 scRNAseq datasets, and it offers me great insights! However, there might be some possible bugs in ecotypes_assign_samples_scRNA.R Rscript in EcoTyper_discovery_scRNA.R pipeline.

First, in ecotypes_assign_samples_scRNA.R, in
https://github.com/digitalcytometry/ecotyper/blob/d1f08bfb42441c91eaffcdfc9e16d4d4b38163b4/pipeline/ecotypes_assign_samples_scRNA.R#L161-L165,  in read_clinical function, clinical$ID might not be able to match to ID column in the annotation.txt file, since ID column in the annotation.txt is single-cell cell ID, and clinical$ID represents sample names.

Second, in https://github.com/digitalcytometry/ecotyper/blob/d1f08bfb42441c91eaffcdfc9e16d4d4b38163b4/pipeline/ecotypes_assign_samples_scRNA.R#L184-L192, if one ecotype is not discovered in any sample, like the following figure 
![image](https://user-images.githubusercontent.com/58244884/144184860-cb7e9cbf-c95c-4400-9d5c-175191dd2647.png)
, the heatmap_all_samples.pdf works fine, but the heatmap_assigned_samples_viridis.png/pdf would produce shift, like the following figure
![image](https://user-images.githubusercontent.com/58244884/144185217-c1a348a6-f008-4ff3-9340-c15e90ccbf21.png)

Third, actually, even when I run example data use ecotypes_assign_samples_scRNA.R, the example data would fail in the process, in 
https://github.com/digitalcytometry/ecotyper/blob/d1f08bfb42441c91eaffcdfc9e16d4d4b38163b4/pipeline/ecotypes_assign_samples_scRNA.R#L65, this might be due to some cell types are not discovered in all samples. If I replace this line with
`	keep_rowname = c(rownames(all_H), rownames(H));
	all_H = rbind.fill(all_H, H);
  rownames(all_H) = keep_rowname`, it would work fine. But I don't know whether this condition has been already excluded by the prerequisite of the cell type chosen.

**Comment by BALuca** [comment]
Hi, 

Thank you for your interest in EcoTyper, and for pointing these three potential issues. For the first one, I just commented out that bit of code, since it has no effect on the output (the pipeline doesn't support annotations for single cell samples yet) and can be confusing to people. I could reproduce and fix the other two issues. The latest commit to the repository should incorporate all these changes. Please let us know if you spot any additional issues!

Best regards,
The EcoTyper team

**Comment by czlcaltech** [comment]
Thanks for your responses, and the new code works fun. I would close this issue.
