### ISSUE TITLE
scRNA-Seq Lymphoma Recovery

### ISSUE THREAD

**Issue by LeonHafner** [digitalcytometry/ecotyper#50]
Hi,
thanks for this amazing tool!
I'm facing some issues recovering my single cell immune data in the Lymphoma EcoTyper., which seems not to be able to sufficiently recover any cell states.
The data comes from patients with mantle cell lymphoma but nevertheless there should be at least some overlap to the DLBCL EcoTyper. It has been preprocessed based on best practice tutorials and is CPM normalized but not log-transformed (I tried with log transformation as well).
The comparison for the B cells, our cell type of interest, looks like this:
![state_assignment_heatmap](https://user-images.githubusercontent.com/60394289/188629069-c3d54834-c933-459b-a9a3-686746db8a7e.png)

As I'm now troubleshooting this I was wondering if you have any ideas what the reason for the bad recovery could be?
I would be very grateful for any advice on how to proceed!

Thanks a lot!

**Comment by cbsteen** [comment]
Hello, 

As you are studying a different lymphoma type, I would recommend that you run the significance analysis when performing scRNA-seq recovery (--z-score set to TRUE), to see whether the states significantly validate in mantle cell lymphoma. This heatmap indicates that you do seem to get some signal for most of the B cell states in your scRNA-seq data, but the significance procedure will help you quantify that.
