### ISSUE TITLE
Minimum coverage of bulk RNASeq samples for  Lymphoma EcoTyper

### ISSUE THREAD

**Issue by auroramaurizio** [digitalcytometry/ecotyper#52]
Hello, and thank you for developing such a nice and useful tool!
I was wondering, is there a minimum coverage-number of reads/sample you suggest to achieve in order to consider the sample a "good" candidate for the analysis?
Thank you,
best,
Aurora

**Comment by cbsteen** [comment]
Hello, thank you for the kind words :) No, no other requirements then standard QC checks you would do for any RNA-seq experiment.
