### ISSUE TITLE
Expression matrix of scRNA-seq

### ISSUE THREAD

**Issue by HengqiLiu** [digitalcytometry/ecotyper#53]
Dear Ecotyper team，

I'm a little confused about the form of the input data about discovery in scRNA-seq data, and I noticed that the example data is counts.

What form of data should I input to run discovery in scRNA-seq data?

Expression matrix field should contain the path to a tab-delimited file containing the expression data, with genes as rows and cells as columns. **_The expression matrix should be in the TPM, CPM or other suitable normalized space._** The users should perform their own quality control of the expression matrix before applying EcoTyper (e.g. to filter low-quality cells, doublets, etc.). However we do not recommend to pre-filter the matrix for variable genes, as EcoTyper performs an internal selection for genes that show cell-type specificity. **_The matrix should have gene symbols on the first column and gene counts for each cell on the next columns._** Column (cells) names should be unique. Also, we recommend that the column names do not contain special characters that are modified by the R function make.names, e.g. having digits at the beginning of the name or containing characters such as space, tab or -:

Thank you,
Hengqi Liu

**Comment by BALuca** [comment]
Hi,

We do not have a strong recommendation about the exact processing, it is up to the users.

Best,
The EcoTyper team
