### ISSUE TITLE
Turoial3: Visium tutorial

### ISSUE THREAD

**Issue by chrismahony** [digitalcytometry/ecotyper#55]
Dear ecotyper,

I have multiple visium samples that I would like to run through ecotpyer. Looking at Tutorial 3, it looks like I would have to run ecotyper on individual samples? IS there a way to run this on all samples at the same time?

Thanks
Chris

**Comment by BALuca** [comment]
Hi Chris,
Thanks for your interest in EcoTyper. Unfortunately there is no way to run multiple visium samples. You would have to run them one by one.
Best,
The EcoTyper team
