### ISSUE TITLE
genes used in input file

### ISSUE THREAD

**Issue by mao223** [digitalcytometry/ecotyper#59]
Good day, I was wondering if you had the corresponding ensembl IDs for the genes used in the input expression matrix?

**Comment by BALuca** [comment]
Hello,

If you are referring to EcoTyper carcinoma input expression matrix, you can match the gene symbols to gene IDs using Gencode v24 annotations: https://www.gencodegenes.org/human/release_24.html.

Best,
The EcoTyper team
