### ISSUE TITLE
fix.by error in Ecotyper_recovery_bulk.txt

### ISSUE THREAD

**Issue by dstueckm** [digitalcytometry/ecotyper#6]
Hello,

I am attempting to run the bulk recovery script on FPKM-normalized bulk RNA-seq data from the KIRP cohort of the TCGA.
I was able to successfully run the web tool, but when I try to run the R script using the same dataset I get the following error:
"Error in fix.by(by.y, y) : 'by' must specify a uniquely valid column"
Running the script with the example data works perfectly fine.

I am calling the R script with all default parameters using the following call:
Rscript EcoTyper_recovery_bulk.R -m /path/to/filepath.txt

I have attached the full output of the R script which includes the error message, and have attached the dataset as a google drive link. Any help in understanding this would be appreciated!

https://drive.google.com/file/d/1-X2OC6zKjZvC2AzoJ8G8hyvgxYnewy_w/view?usp=sharing

Thank you,
Danie
[captureError.txt](https://github.com/digitalcytometry/ecotyper/files/7650447/captureError.txt)
l

**Comment by BALuca** [comment]
Dear Danie,

Thank you for reporting this issue and providing the debug data. We have been able to reproduce the issue and fix it. The latest commit of the repository should incorporate the fix. Please let us know if you encounter any additional problems. 

Best,
The EcoTyper team

**Comment by dstueckm** [comment]
Thank you, seems to work perfectly with the latest version
