### ISSUE TITLE
Dependency unmentioned in README

### ISSUE THREAD

**Issue by SyouTono242** [digitalcytometry/ecotyper#61]
Hiiiii!

I've been trying to play with ecotyper and I found that it requires some more dependencies than what's mentioned in the README. So far, the extra dependencies I found to be necessary to run tutorial 1 are **Biobase** and **xquartz** (for running on mac only). It'd be great if you could add those to the set-up guides, or, even better, make an installation script that checks for dependencies and installs them automatically if needed.  It'd save a lot of the hassles. 

After building up all the dependencies, so far it's working perfectly well for me. Thank you for building this amazing tool!

**Comment by BALuca** [comment]
Hi,

Thank you for your interest in EcoTyper and for reporting the missing dependencies. We updated the README accordingly.

Best,
The EcoTyper team
