### ISSUE TITLE
Estimating cell-type fractions from bulk RNA

### ISSUE THREAD

**Issue by danieljrichard** [digitalcytometry/ecotyper#62]
Hello,
I've run Ecotyper discovery to define new cell-states for a set of seven different cell types in an scRNA-seq dataset.
Now I've run the cell-type recovery (Tutorial 1) on ~50 bulk RNA samples, and have estimated cell-state abundances for each cell type per-sample. However, I'm wondering if there's a way to define the fraction of cell-types for a given bulk sample, similar to what would be output with something like CIBERSORTX. Like sample1 has 40% of cell type 1 (of which, 20% is state 1, 30% state2, etc.), 60 % of cell type 2 (etc.)

Looking through the source code, I have a rough idea how the cell-state abundances are calculated using the NMF data, but am not sure if this math is appropriate for cell-fraction estimation.

Thanks,

Daniel Richard

**Comment by BALuca** [comment]
Hi Daniel,

EcoTyper does not support the direct estimation of cell type abundances in bulk data at the recovery stage. For this task, you would need to use CIBERSORTx or similar methods. I hope it helps.

Best,
The EcoTyper team
