### ISSUE TITLE
Issue with cell type specific genes when performing scRNAseq discovery 

### ISSUE THREAD

**Issue by dkwon6** [digitalcytometry/ecotyper#63]
I have been trying to run EcoTyper scRNAseq discovery on a scRNAseq dataset. When I set the config Filter genes to "cell type specific", I get the following error: 

Step 2 (cell state discovery on correrlation matrices): Calculating correlation matrices...
Warning message:
There are more than 2500 single cells available for cell type 'Epithelial.cells'. Subsampling to 2500 cells.

Filtering 'CD4.Naive' profiles for cell type specific genes...
---> Checking zero-variance data...
---> Total number of variables: 2500
---> WARNING: 2500 variables found with zero variance
---> Maximum number of splits: floor(n/2) = 0
---> WARNING: number of splits nSplit > 0
---> WARNING: using maximum number of splits: nSplit = 0
Error in fastCor(scaled_data) : invalid nSplit: 0
Execution halted
Error in RunJobQueue() :
EcoTyper failed. Please check the error message above!
Execution halted

However, when I manually set the Filter genes to a number (e.g. I've done 1000 and 2000 in my analyses), it runs without any issues.

I'd be happy to email an anonymized subsetted scRNAseq data if needed. 

Thanks

**Comment by BALuca** [comment]
Hello,

Thanks for your interest in EcoTyper. Would it be possible to send us a reproducible example at ecotyper.stanford@gmail.com?

Best,
The EcoTyper team
