### ISSUE TITLE
How to get the cibersortx token?

### ISSUE THREAD

**Issue by dufeng311** [digitalcytometry/ecotyper#66]
Hello, I would like to use ecotyper for discovering cell states and analyzing spatial transcriptomics data, but I need to apply for a CIBERSORTx token. Would you please tell me how should I proceed with the application process? Thank you very much!

**Comment by BALuca** [comment]
Hi,
You would have to apply for a CIBERSORTx token on [the CIBERSORTx website](https://cibersortx.stanford.edu/download.php).
Best,
The EcoTyper team
