### ISSUE TITLE
Using an existing cancer single-cell atlas dataset as discovery?

### ISSUE THREAD

**Issue by WangKang-Leo** [digitalcytometry/ecotyper#67]
I am just wondering whether I can apply ecotyper on our bulk RNA-seq using an existing cancer single-cell atlas dataset (such as https://www.nature.com/articles/s41588-021-00911-1), which has been well annotated. Thanks!

**Comment by BALuca** [comment]
Hi,
EcoTyper does not currently allow label transfer from pre-defined scRNA-seq classes to bulk data.
Best,
The EcoTyper team
