### ISSUE TITLE
step4 error

### ISSUE THREAD

**Issue by sayhello854123** [digitalcytometry/ecotyper#68]
Step 4 (extracting cell state information)...
Extracting cell states information for: Dendritic 
Extracting cell states information for: M1.macrophage 
Extracting cell states information for: M2.macrophage 
Extracting cell states information for: Monocyte 
Error in dimnames(x) <- dn : 
  length of 'dimnames' [1] not equal to array extent
Calls: rownames<- -> rownames<-
Execution halted
Error in dimnames(x) <- dn : 
  length of 'dimnames' [1] not equal to array extent
Calls: rownames<- -> rownames<-
Execution halted
Error in dimnames(x) <- dn : 
  length of 'dimnames' [1] not equal to array extent
Calls: rownames<- -> rownames<-
Execution halted
Error in RunJobQueue() : 
  EcoTyper failed. Please check the error message above!
Execution halted

**Comment by BALuca** [comment]
Hello, 
Apologize for the issue you are encountering. Would it be possible to send us a reproducible example at ecotyper.stanford@gmail.com for debug?
Best,
The EcoTyper team

**Comment by sayhello854123** [comment]
Thank you for letting me know that you have resolved the issue. I'm glad I
could assist. If you have any further questions or need help in the future,
feel free to reach out. Have a great day!

BALuca ***@***.***> 于2023年6月29日周四 21:55写道：

**Comment by sayhello854123** [comment]
Thank you for letting me know that you have resolved the issue. I'm glad I
could assist. If you have any further questions or need help in the future,
feel free to reach out. Have a great day!

chuichui wang ***@***.***> 于2023年7月6日周四 17:04写道：

**Comment by sayhello854123** [comment]
Thank you for reaching out. I wanted to inform you that I have successfully
resolved the issue I was facing. Your letter was greatly appreciated and I
would like to express my gratitude for your support.

BALuca ***@***.***> 于2023年6月29日周四 21:55写道：

**Comment by sayhello854123** [comment]
*Tutorial 4*
<https://github.com/digitalcytometry/ecotyper#tutorial-4-de-novo-discovery-of-cell-states-and-ecotypes-in-bulk-data>:
 I
have an account, but I don't know how to obtain a token.

chuichui wang ***@***.***> 于2023年7月6日周四 17:07写道：

**Comment by BALuca** [comment]
Hi, 
You can obtain a token from the CIBERSORTx website: https://cibersortx.stanford.edu/
Best,
The EcoTyper team
