### ISSUE TITLE
Change the Size of Output Images? 

### ISSUE THREAD

**Issue by dmiyagi** [digitalcytometry/ecotyper#70]
Hi, I am wondering if there is a way to change the size of the images outputed by ecotyper? I am wanting to add 4-5 rows of metadata to the graphs but it gets cut off when I add that many. I tried to look through the docs and other questions but wasn't able to find the answer to this. Thanks

**Comment by BALuca** [comment]
Hi,

Unfortunately EcoTyper does not support this feature yet. I will put it on the updates list, but might take a while until we get to implement it. I can indicate the changes that you can make to the EcoTyper code to increase the plot size. To be able to guide you, please let us know the type of EcoTyper analysis you are running at ecotyper.stanford@gmail.com. 

Best regards,
The EcoTyper team
