### ISSUE TITLE
Error:       failed to create symbolic link 'datasets/bulk/bulk_lung_data/data.txt': Operation not permitted

### ISSUE THREAD

**Issue by wanglu2014** [digitalcytometry/ecotyper#72]
Rscript EcoTyper_recovery_bulk.R -d Carcinoma -m /media/sf_transQiime/ecotyper-master/example_data/bulk_lung_data.txt -a /media/sf_transQiime/ecotyper-master/example_data/bulk_lung_annotation.txt -c Tissue -o RecoveryOutput2
ln: failed to create symbolic link 'datasets/bulk/bulk_lung_data/data.txt': Operation not permitted
ln: failed to create symbolic link 'datasets/bulk/bulk_lung_data/annotation.txt': Operation not permitted
Running cell state recovery on: CD4.T.cells...
Running cell state recovery on: Monocytes.and.Macrophages...
Running cell state recovery on: Dendritic.cells...
Running cell state recovery on: CD8.T.cells...
Running cell state recovery on: PMNs...
Running cell state recovery on: NK.cells...
Running cell state recovery on: Mast.cells...
Running cell state recovery on: Fibroblasts...
Running cell state recovery on: B.cells...
Running cell state recovery on: PCs...

This is my code. I have check whether bulk_lung_data.txt and bulk_lung_annotation.txt existed in /example_data/. And I have tried to create data.txt and annotation.txt in /media/sf_transQiime/ecotyper-master/datasets/bulk/bulk_lung_data/, then get the same error.

**Comment by BALuca** [comment]
Hello,

It seems that you do not have permissions to write in the folder containing EcoTyper (/media/sf_transQiime/ecotyper-master). We would recommend checking that with your system administrator.
