### ISSUE TITLE
Will the marker gene vary with different discovery datasets?

### ISSUE THREAD

**Issue by LynnChan99** [digitalcytometry/ecotyper#73]
In your published article supplementary, the top 10 marker genes of 69 cell states were given, so , will the marker gene vary with different discovery datasets? or it just be the marker gene under your pan-cancer frame?

**Comment by BALuca** [comment]
Hi,

The markers presented in the paper are the pan-carcinoma ones. You can explore the histology-specific ones on our [website](https://ecotyper.stanford.edu/carcinoma/#shiny-tab-explore) in the section Explore Cell States & Ecotypes -> Cell State Signatures.

**Comment by LynnChan99** [comment]
The marker genes are belong to the supplementary of your Cell article, I noticed that they are not similiar to the genes presented in the heatmap.So, what's the difference?
---- Replied Message ----
| From | ***@***.***> |
| Date | 08/25/2023 17:06 |
| To | ***@***.***> |
| Cc | LynnChan99 ***@***.***>,
Author ***@***.***> |
| Subject | Re: [digitalcytometry/ecotyper] Will the marker gene vary with different discovery datasets? (Issue #73) |

Hi,

The markers presented in the paper are the pan-carcinoma ones. You can explore the histology-specific ones on our website in the section Explore Cell States & Ecotypes -> Cell State Signatures.

**Comment by BALuca** [comment]
Which markers, heatmap and supplementary table?

**Comment by LynnChan99** [comment]
Ok, I see. In your supplementary, the top 10 genes are from the single-cell data, but what I noticed in the pheatmap in ecotyper websites before are from core genes in cibersortx. If I want to calculate the abundance by ssgsea (I have already get the abundance of each of them seperately by ecotyper, and I need to calculate some combination of the specific cell states) , which gene list should I use?


Thanks, sorry for asking so many questions.


Best regards,
Chan.


在 2023-08-25 17:27:14，"BALuca" ***@***.***> 写道：

Which markers, heatmap and supplementary table?

**Comment by BALuca** [comment]
Hi Chan,

I would recommend the single-cell version, since it is more comprehensive. I hope it helps!

Bogdan

**Comment by LynnChan99** [comment]
Thanks!It's very helpful of your advice.


Hope you have a good day!
---- Replied Message ----
| From | ***@***.***> |
| Date | 08/25/2023 19:10 |
| To | digitalcytometry/ecotyper ***@***.***> |
| Cc | LynnChan99 ***@***.***>,
Author ***@***.***> |
| Subject | Re: [digitalcytometry/ecotyper] Will the marker gene vary with different discovery datasets? (Issue #73) |

Hi Chan,

I would recommend the single-cell version, since it is more comprehensive. I hope it helps!

Bogdan
