### ISSUE TITLE
Error in consensus + nrun(x) * consensus(x) : non-conformable arrays

### ISSUE THREAD

**Issue by WangKang-Leo** [digitalcytometry/ecotyper#74]
Dear 

I followed the Tutorial 5. De novo Discovery of Cell States and Ecotypes in scRNA-seq Data, where I used the brca single cell atlas as input. After finishing NMF step, ecotyper reported errors. Could you please have a look at my attached log file
[slurm-1178357.txt](https://github.com/digitalcytometry/ecotyper/files/12494300/slurm-1178357.txt), and what's your suggestion for my situation?

Thanks
Kang

**Comment by BALuca** [comment]
Hi Kang,

Thanks for you interest in EcoTyper. The error you are getting is very unusual, and hard to debug without seeing the data. My guess would be that you partially ran the EcoTyper once and then modified the input expression matrices. When running it the second time, some of the intermediary results from the first rule interfere with the current run and make it crash. I would suggest either deleting the folder "EcoTyper/brca_atlas_scRNA/Cell_type_specific_genes" and start fresh, or changing the name of the discovery dataset name in the config file (brca_atlas_scRNA), to force EcoTyper use a new directory for intermediary files. If this does not solve the problem, my second guess would be that some cell types have very few cells, and that makes NMF behave unpredictably. If that is the case, I would suggest filtering those cell types or merging them with a similar cell type. I hope it helps.

Best,
The EcoTyper team

**Comment by WangKang-Leo** [comment]
> Hi Kang,
> 
> Thanks for you interest in EcoTyper. The error you are getting is very unusual, and hard to debug without seeing the data. My guess would be that you partially ran the EcoTyper once and then modified the input expression matrices. When running it the second time, some of the intermediary results from the first rule interfere with the current run and make it crash. I would suggest either deleting the folder "EcoTyper/brca_atlas_scRNA/Cell_type_specific_genes" and start fresh, or changing the name of the discovery dataset name in the config file (brca_atlas_scRNA), to force EcoTyper use a new directory for intermediary files. If this does not solve the problem, my second guess would be that some cell types have very few cells, and that makes NMF behave unpredictably. If that is the case, I would suggest filtering those cell types or merging them with a similar cell type. I hope it helps.
> 
> Best, The EcoTyper team

Thank you for your prompt and helpful reply, I resume the analyses several times before. Now I would like to run it from scratch! Let's see!
