### ISSUE TITLE
Can't align to any ecotype

### ISSUE THREAD

**Issue by WangKang-Leo** [digitalcytometry/ecotyper#75]
Dear 

Thanks for this very brilliant tool, which enables us to do more specific immune deconvolution! After I successfully running EcoTyper_discovery_scRNA.R for the public breast cancer single cell atlas dataset, I failed to run EcoTyper_recovery_bulk.R using above self-defined discovery. It showed "Error: No samples were assigned to ecotypes!
Execution halted". However, I can run EcoTyper_recovery_bulk.R for my bulk RNA-seq using Mydiscovery_scRNA_CRC that I generated based on your tutorial. Do you have any suggestions?

Thanks in advance!
Kang

**Comment by BALuca** [comment]
Hi Kang, 

The error suggests that the ecotypes derived in your data are not robust enough. Therefore, they are not recoverable in external data. Increasing the sample size, or evaluating the parameters used for discovery (e.g. the Cophenetic coefficient cutoff, gene selection strategy in field "Filter genes") might help.

Best,
The EcoTyper team
