### ISSUE TITLE
Tutorial 3 error parse_args_output

### ISSUE THREAD

**Issue by Torti11** [digitalcytometry/ecotyper#78]
Hi,

I tried running tutorial 3 with my Visium data and I got this error. Then, I tried running tutorial 3 with the example data and I got the same error:
C:\Users\Downloads\ecotyper-master>"C:\Program Files\R\R-4.3.1\bin\Rscript.exe" C:\Users\Downloads\ecotyper-master\EcoTyper_recovery_visium.R -c C:\Users\Downloads\ecoptyper-master\config_recovery_visium.yml
Error in if (grepl("^\\{|^\\[", output)) { : the condition has length > 1
Calls: <Anonymous> -> parse_args_output
Execution halted

This error appears independently that the user and token are provided or not in the YAML configuration file. I tried removing the already generated output in VisiumOutput folder and the same error keeps. By the way, I could run the example Bulk data from tutorial 1 without any problems, therefore, EcoTyper is working in my computer but not for Visium data.
The previous command was run in the Command Promt of a Windows 11 Pro.
Could you help me to figure out the problem, please?

Many thanks in advance!

**Comment by BALuca** [comment]
Hello,

EcoTyper has not been tested Windows. So, we cannot guarantee that all tutorials work there. Unfortunately, it is hard to debug the problem from the message above. Causes can include a Windows-specific error, a problem with the configuration file, or a bug in the code. Would it be possible to run it on a Linux/Mac machine? If the error persists, could you please send us the configuration file you used at ecotyper.stanford@gmail.com? 

Best regards,
The EcoTyper team
