### ISSUE TITLE
Question with TCGA cell state assignment from ecotyper website

### ISSUE THREAD

**Issue by WuRAFY** [digitalcytometry/ecotyper#79]
Hi, 
  I downloaded the file "TCGA Cell State Assignments" from ecotyper website (https://ecotyper.stanford.edu/carcinoma/session/195022ffeaca30b8ec3d57b75d00100a/download/cell_state_assignments_download?w=). Then I found there are more cell states in the file than in the article. And the abundance of cell is too low compared to the heatmap scale in the article (e.g. the maximum abundance is 0.2089279 and even no cell abundance > 0.1 found in LUAD). 
  Can you help? Much thanks

**Comment by BALuca** [comment]
Hello,

Thank you for letting us know about the discrepancy in the download section. The website was, indeed, providing a wrong output file. We fixed that, and the download file should now contain 69 cell states. Please let us know if you notice any other issues.

Best regards,
The EcoTyper team
