### ISSUE TITLE
about Token of CIBERSORTx

### ISSUE THREAD

**Issue by BolinLiuu** [digitalcytometry/ecotyper#81]
We are trying to use ecotyper in our RNA-Seq datasets with de novo model in ecotyper.
We need the Token of CIBERSORTx for docker images. We have asked for the Token from the website, but it's still pending approval.
Could you please share me the Token of CIBERSORTx?
My email address is liubolin@ihcams.ac.cn
Thanks!

**Comment by BALuca** [comment]
Hi, 

Unfortunately, that would need to be obtained form the CIBERSORTx website.

Best,
The EcoTyper team

**Comment by yanwuanxin** [comment]
<img width="705" alt="72809d42238141991993951725b8565" src="https://github.com/digitalcytometry/ecotyper/assets/61311726/0ebae59d-307b-424a-a896-60784d7ea6d6">

请问Token是什么，在哪获取

**Comment by yanwuanxin** [comment]
<img width="705" alt="72809d42238141991993951725b8565" src="https://github.com/digitalcytometry/ecotyper/assets/61311726/fc4026cd-2b4b-43e0-a0fc-153969aedc43">

I have already registered an account, but what 'token' is and where to obtain it?
