### ISSUE TITLE
ecotyper for GeoMx

### ISSUE THREAD

**Issue by chrispatsalis** [digitalcytometry/ecotyper#82]
Hello,

I'm working with GeoMx spatial transcriptomics data where several user-selected ROI's within each slide are sequenced, as opposed to Visium where you get single-cell(ish) resolution. Would it be appropriate to use ecotyper for GeoMx spatial transcriptomics data? If so, what would be the approach? Since entire ROI's are sequenced and there are no cell coordinates, I considered treating each ROI as independent and using the bulk RNA-seq method. Would this be a reasonable thing to do? 

Chris

**Comment by BALuca** [comment]
Hi Chris,

This is a tricky question. I guess that it depends on your ROI size. The main difference between the recovery of cell states in bulk vs. Visium is that in the latter the state abundances are weighted by the cell fraction to account for the spots in which that cell type might be missing. In your case, you could probably run the bulk RNA-seq method to get the cell state abundance. But then you might need to do a post processing to account for cases in which the cell type is missing from the ROI. This is especially important when the ROI is small, therefore a higher likelihood that some cell types are missing. I hope it helps.

Best regards,
The EcoTyper team
