### ISSUE TITLE
errors with EcoTyper_recovery_bulk.R

### ISSUE THREAD

**Issue by tjogzt** [digitalcytometry/ecotyper#86]
In tutorial 1, when I ran 
Rscript EcoTyper_recovery_bulk.R -d Carcinoma -m example_data/bulk_lung_data.txt -a example_data/bulk_lung_annotation.txt -c Tissue -o RecoveryOutput
It showed the following error information:

Running cell state recovery on: Dendritic.cells...
Running cell state recovery on: CD8.T.cells...
Running cell state recovery on: Monocytes.and.Macrophages...
Running cell state recovery on: PMNs...
Running cell state recovery on: Fibroblasts...
Running cell state recovery on: PCs...
Running cell state recovery on: NK.cells...
Running cell state recovery on: B.cells...
Running cell state recovery on: Mast.cells...
Running cell state recovery on: CD4.T.cells...
错误: R: UnableToOpenBlob `/var/folders/1z/bp5tmh3j14n4wdqghk64wcg00000gn/T//RtmpWdGPuG/.heatmap_body_8e298dcba81b6519e384a7170581a0ad_1_1129d95228a66f.png': No such file or directory @ error/blob.c/OpenBlob/2960
停止执行
错误: R: UnableToOpenBlob `/var/folders/1z/bp5tmh3j14n4wdqghk64wcg00000gn/T//Rtmpiuu9g2/.heatmap_body_8e298dcba81b6519e384a7170581a0ad_1_1129dd2b2751ee.png': No such file or directory @ error/blob.c/OpenBlob/2960
停止执行
错误: R: UnableToOpenBlob `/var/folders/1z/bp5tmh3j14n4wdqghk64wcg00000gn/T//RtmpNTFqPU/.heatmap_body_8e298dcba81b6519e384a7170581a0ad_1_1129e55a7338a8.png': No such file or directory @ error/blob.c/OpenBlob/2960
停止执行
错误: R: UnableToOpenBlob `/var/folders/1z/bp5tmh3j14n4wdqghk64wcg00000gn/T//RtmpqyP5vd/.heatmap_body_8e298dcba81b6519e384a7170581a0ad_1_1129db42cbad3e.png': No such file or directory @ error/blob.c/OpenBlob/2960
停止执行
错误: R: UnableToOpenBlob `/var/folders/1z/bp5tmh3j14n4wdqghk64wcg00000gn/T//RtmpSgmAJn/.heatmap_body_8e298dcba81b6519e384a7170581a0ad_1_1129e21d00a93e.png': No such file or directory @ error/blob.c/OpenBlob/2960
停止执行
错误: R: UnableToOpenBlob `/var/folders/1z/bp5tmh3j14n4wdqghk64wcg00000gn/T//RtmpOam5U8/.heatmap_body_8e298dcba81b6519e384a7170581a0ad_1_1129d7605271e2.png': No such file or directory @ error/blob.c/OpenBlob/2960
停止执行
错误: R: UnableToOpenBlob `/var/folders/1z/bp5tmh3j14n4wdqghk64wcg00000gn/T//RtmpEioSJy/.heatmap_body_8e298dcba81b6519e384a7170581a0ad_1_1129d5395ea066.png': No such file or directory @ error/blob.c/OpenBlob/2960
停止执行
Running cell state recovery on: Epithelial.cells...
Running cell state recovery on: Endothelial.cells...
错误: R: UnableToOpenBlob `/var/folders/1z/bp5tmh3j14n4wdqghk64wcg00000gn/T//RtmpwaPriA/.heatmap_body_8e298dcba81b6519e384a7170581a0ad_1_1129e37560e85f.png': No such file or directory @ error/blob.c/OpenBlob/2960
停止执行
错误: R: UnableToOpenBlob `/var/folders/1z/bp5tmh3j14n4wdqghk64wcg00000gn/T//Rtmp1xNaJX/.heatmap_body_8e298dcba81b6519e384a7170581a0ad_1_1129df252b2a93.png': No such file or directory @ error/blob.c/OpenBlob/2960
停止执行
错误: R: UnableToOpenBlob `/var/folders/1z/bp5tmh3j14n4wdqghk64wcg00000gn/T//RtmpEOf476/.heatmap_body_8e298dcba81b6519e384a7170581a0ad_1_1129e6780f1b31.png': No such file or directory @ error/blob.c/OpenBlob/2960
停止执行
错误: R: UnableToOpenBlob `/var/folders/1z/bp5tmh3j14n4wdqghk64wcg00000gn/T//RtmpQN2n46/.heatmap_body_8e298dcba81b6519e384a7170581a0ad_1_112a7c4c0f3b6d.png': No such file or directory @ error/blob.c/OpenBlob/2960
停止执行
错误: R: UnableToOpenBlob `/var/folders/1z/bp5tmh3j14n4wdqghk64wcg00000gn/T//RtmpSDydw8/.heatmap_body_8e298dcba81b6519e384a7170581a0ad_1_112a77239774a3.png': No such file or directory @ error/blob.c/OpenBlob/2960
停止执行
Error in RunJobQueue() : 
  EcoTyper failed. Please check the error message above!
停止执行

How to solve it? I need your help. Thanks !

**Comment by cbsteen** [comment]
Thank you for your interest in EcoTyper. Sorry for the late response. Were your running EcoTyper locally on your computer? Perhaps there was something else running at the same time that prevented from opening the files.

**Comment by cbsteen** [comment]
Closing issue
