### ISSUE TITLE
How can I solve this issue?

### ISSUE THREAD

**Issue by LynnChan99** [digitalcytometry/ecotyper#87]
Hi, I am trying to run scRNA data on Ecotyper recently. However, I encountered some issues that I can't solve, thus wanted to seek your help.

I dont' know how to solve it, it didn't show any useful information about the error message as following:

(base) root@interactive52680:/home/chenxiaolin/ecotyper-master# Rscript EcoTyper_recovery_scRNA.R -d Carcinoma -m ecotyper_scRNA/GSE176078.expr.txt -a ecotyper_scRNA/GSE176078.anno.txt -o RecoveryOutput -s 60
The annotation file contains column 'Sample', and more than half of the cell types are present in the recovery dataset. Will perform ecotype recovery.
Running cell state recovery on cell type: PCs...
Running cell state recovery on cell type: Endothelial.cells...
Running cell state recovery on cell type: CD4.T.cells...
Running cell state recovery on cell type: Dendritic.cells...
Running cell state recovery on cell type: CD8.T.cells...
Running cell state recovery on cell type: Epithelial.cells...
Running cell state recovery on cell type: Monocytes.and.Macrophages...
Running cell state recovery on cell type: B.cells...
Running cell state recovery on cell type: NK.cells...
Running cell state recovery on cell type: Fibroblasts...
Killed
Killed
Downsampling cell type 'Dendritic.cells' to 60 cells...
Downsampling cell type 'NK.cells' to 60 cells...
Downsampling cell type 'B.cells' to 60 cells...
Downsampling cell type 'CD8.T.cells' to 60 cells...
Downsampling cell type 'Monocytes.and.Macrophages' to 60 cells...
Downsampling cell type 'Fibroblasts' to 60 cells...
Downsampling cell type 'CD4.T.cells' to 60 cells...
Downsampling cell type 'Epithelial.cells' to 60 cells...
Error in RunJobQueue() : 
  EcoTyper failed. Please check the error message above!
Execution halted

Thank you again for your attention. I am really appreciated for your help.

**Comment by cbsteen** [comment]
This seems to be related to a memory issue, for example if you are running EcoTyper in an interactive session on a server/cluster. Try allocating more memory, especially when working with scRNA-seq data.

**Comment by LynnChan99** [comment]
It seems not related to the memory. I updated the running memory of server to 256/512GB, still can’t work on 27 scRNA samples

---- Replied Message ----
| From | Chloé B. ***@***.***> |
| Date | 06/19/2024 01:37 |
| To | digitalcytometry/ecotyper ***@***.***> |
| Cc | LynnChan99 ***@***.***>,
Author ***@***.***> |
| Subject | Re: [digitalcytometry/ecotyper] How can I solve this issue? (Issue #87) |

Closed #87 as completed.

**Comment by cbsteen** [comment]
How many cells do you have? I would try downsampling the file prior to running EcoTyper.

**Comment by LynnChan99** [comment]
I also tried downsamples, still failed.

---- Replied Message ----
| From | Chloé B. ***@***.***> |
| Date | 06/19/2024 01:46 |
| To | digitalcytometry/ecotyper ***@***.***> |
| Cc | LynnChan99 ***@***.***>,
Author ***@***.***> |
| Subject | Re: [digitalcytometry/ecotyper] How can I solve this issue? (Issue #87) |

How many cells do you have? I would try downsampling the file prior to running EcoTyper.

**Comment by cbsteen** [comment]
How big is your scRNA-seq dataset? How many cells? You tried downsampling your input file prior to running EcoTyper? If so there could be an issue with the formatting of your input file.

**Comment by LynnChan99** [comment]
Around 500Mb and 170,000 cells. I would try it again, thank u so much.

---- Replied Message ----
| From | Chloé B. ***@***.***> |
| Date | 06/19/2024 04:10 |
| To | digitalcytometry/ecotyper ***@***.***> |
| Cc | LynnChan99 ***@***.***>,
Author ***@***.***> |
| Subject | Re: [digitalcytometry/ecotyper] How can I solve this issue? (Issue #87) |

How big is your scRNA-seq dataset? How many cells? You tried downsampling your input file prior to running EcoTyper? If so there could be an issue with the formatting of your input file.

**Comment by LynnChan99** [comment]
Sorry, could you please share how to extract and save the expression matrix from standard single-cell data in R? I think the issue might be with the data form.
