### ISSUE TITLE
Discovery/recovery function & functional states like CancerSEA

### ISSUE THREAD

**Issue by LiuCanidk** [digitalcytometry/ecotyper#90]
Hi,
I notice that the Ecotyper_Recovery_bulk.R function, recovers multiple discovered carcinoma cell states (published in the cell 2021 ecotyper paper) from bulk RNA-seq data. I'm not so familar with the machine learning algorithms, but I found this processing was just like first deconvolution, and then annotation, and annotation was based on some prior knowledge (here is carcinoma cell sates, and typically in scRNA-seq is marker genes).

So is that possible to change the annotation database from the carcinoma states (I note most are TME cell types), to some functional annotations? e.g., CancerSEA database, which is easier for users to infer biological meanings.

All above is just my immature thought. I would appreciate it if reply or discussion is available.

**Comment by cbsteen** [comment]
Thank you for your interest in EcoTyper. You can add annotations from external databases in the annotation file of your input dataset for example. That way you can interrogate EcoTyper cell states for enrichment or depletion of previously known functional annotations.
