### ISSUE TITLE
Ecotyper website server

### ISSUE THREAD

**Issue by bplet01** [digitalcytometry/ecotyper#92]
I tried to use the Ecotyper website to upload my own bulk expression data but it would not take my file or it would disconnet me from the Ecotyper server. Are there currently issues with the server? 
https://ecotyper.stanford.edu/carcinoma/

**Comment by erinlbrown** [comment]
Hi, thanks for your interest in EcoTyper! We are not seeing any issues with the web app server currently. Could you try again and let us know if you still encounter the same issue? You might also confirm that your file size is under the web app limit of 200MB. 

Thank you!

**Comment by bplet01** [comment]
Thanks, I am still having the same issue and the file size is below the 200 MB limit.

**Comment by erinlbrown** [comment]
Since we are not seeing any issues with the web app server on our end, it is difficult to debug without more information. If the issue is still not resolved, could you share your data with us via email at [ecotyper.stanford@gmail.com](mailto:ecotyper.stanford@gmail.com)?

**Comment by bplet01** [comment]
I have reached out to the gmail account before but had not received a response. I will try again.
