### ISSUE TITLE
EcoTyper failed - EcoTyper_recovery_bulk.R

### ISSUE THREAD

**Issue by AimSchina** [digitalcytometry/ecotyper#93]
Hey, thank you for providing this beautiful software! I have been running ecotyper on different public bulk RNA-Seq datasets, and one is giving me trouble:

> Running cell state recovery on: B.cells...
> Running cell state recovery on: PCs...
> Running cell state recovery on: CD8.T.cells...
> Running cell state recovery on: CD4.T.cells...
> Error: No samples were assigned to cell states for cell type: CD4.T.cells
> Execution halted
> Running cell state recovery on: NK.cells...
> Running cell state recovery on: Monocytes.and.Macrophages...
> Running cell state recovery on: Dendritic.cells...
> Running cell state recovery on: Mast.cells...
> Running cell state recovery on: PMNs...
> Running cell state recovery on: Fibroblasts...
> Running cell state recovery on: Endothelial.cells...
> Running cell state recovery on: Epithelial.cells...
> Error in RunJobQueue() : 
>   EcoTyper failed. Please check the error message above!
> Execution halted

I am wondering whether it fails because samples were not assigned to cell stated for the CD4 T cells, so there cannot be any ecotype assignment...

I would appreciate your feedback, thank you!

**Comment by cbsteen** [comment]
Yes, without knowing more about the input dataset, I believe you are correct. Perhaps your input dataset is too small for successful recovery.
