### ISSUE TITLE
Running bulk recovery with published cell states

### ISSUE THREAD

**Issue by WJRDW** [digitalcytometry/ecotyper#94]
Hi!

Thank you very much for building this amazing tool!
I'm interested in recovering cell states and ecotypes from bulk RNA sequencing data using published cell states in sarcomas (https://www.ncbi.nlm.nih.gov/pmc/articles/PMC11058033/).
The cell state markers of the different identified cell states are publicly available in the supplementary information of the article in an excel file. 
![cell state markers](https://github.com/digitalcytometry/ecotyper/assets/69242147/189e63f0-b78f-46c3-bc6e-bfd37750e579)
I succesfully installed all components needed to run the bulk recovery analysis and can run the examples. My question is how I should structure the published cell states (should the markers for each cell type be in a separate .txt file and seperate folder?) and how to feed it into the algorithm. 
Thank you very much for your help!

**Comment by cbsteen** [comment]
Thank you for your interest in EcoTyper. I would recommend to follow [the instructions provided by the authors](https://github.com/ejmoding/sarcomaecotyper).
