### ISSUE TITLE
Can it use in Non-tumor anlysis?

### ISSUE THREAD

**Issue by fengqlin** [digitalcytometry/ecotyper#95]
I am currently using proteomics data to study sepsis. I'm not sure if this software can be used to study the development stages of various diseases other than tumors. I would appreciate some suggestions on the principles behind using this software for such research. Thank you.

**Comment by cbsteen** [comment]
Hello, thank you for your interest in EcoTyper. we have not developed and applied EcoTyper with proteomics data, so we cannot make a recommendation at this point. It is possible to use EcoTyper to study disease states other than cancer, we would recommend having data available for validation. For example in the Carcinoma and Lymphoma EcoTyper papers (Cell 2021 and Cancer Cell 2021), we use scRNA-seq data to validate the states discovered with EcoTyper.
